version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: telegram_bot_db
    environment:
      POSTGRES_USER: telegrambot
      POSTGRES_PASSWORD: telegrambot_password
      POSTGRES_DB: telegrambot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
